### ISSUE TITLE
Document autostart of virtual machines

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/ovs-documentation#24]
## Problem description
There can be issues with the autostarting of virtual machines that require ASDs. This is not an issue of OVS but can be problematic for our clients. We should include a solution in our documentation.

https://github.com/openvstorage/framework/issues/829
## Possible solution
I will add a solution to this issue if I found one. Currently the temporary one can be documented.

**Comment by khenderick** [comment]
We have a few items to document/consider:
* If asds (or the alba backend services themself) take more time to start than the volumedriver, the volumedriver won't automatically re-try starting it's volumes once the backend is running
* * This is also the case for any other backend
* * A manual restart of these volumes might be mandatory
* If the volumedriver service is started, the volumedriver might still be working on some internal flows before it can start accepting reads/writes. When adding a vPool the framework handles this by listening to an event the volumedriver puts on RMQ,
* * This means we cannot use upstart dependencies
* I'm not sure whether there's a solution better than "wait X minutes after startup*
* * If requested by users/customers, we might add some service that does the RMQ event checking so the users/customers can use plain service dependencies towards that service.

**Comment by wimpers** [comment]
@JeffreyDevloo Currently in the administration Gitbook there is a page for stopping and restarting the cluster https://openvstorage.gitbooks.io/administration/content/Administration/shutdownrestart.html Anything you would like to see added there?

**Comment by wimpers** [comment]
>  When adding a vPool the framework handles this by listening to an event the volumedriver puts on RMQ,

@khenderick what is the best way for users to do the same?

**Comment by khenderick** [comment]
@wimpers, since that's not a "public" functionality user cannot use that event reliable as it might change in between versions. At this point, I don't think users can reliably know when the volumedriver is started. I think a feature request on the volumedriver repo might be a good idea to provide this.

**Comment by wimpers** [comment]
FR created.

**Comment by wimpers** [comment]
@khenderick the FR is now created on the voldrv repo. I'm wondering if the volumedriver needs to provide this API. Since the framework already does the checking (the framework handles this by listening to an event the volumedriver puts on RMQ), why doesn't the framework expose the volumedriver status as its API?

**Comment by khenderick** [comment]
We only do the checking when we create a vpool (since after the volumedriver starts we still need to do some actions), but we don't keep track of its status afterwards, so the framework has no knowledge either.

The framework could provide an unreliable API call if we always process the event and let this result in an answer whether the volumedriver is running or not. But when the system reboots, the framework might not be running yet when the event is send, so would be lost and we would report the service as not running.

**Comment by wimpers** [comment]
So it fundamentally needs to be tackled by the voldrv team. To be discussed if we expose it as API in the framework?

**Comment by khenderick** [comment]
Yes, I think so.
